name: Build and Deploy Code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: url
      ENVIRONMENT: dev
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: team-manangement
          POSTGRES_PASSWORD: 123
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Pull Repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"
          cache: "pip"
      - name: Update `pip`
        run: python -m pip install --upgrade pip
      - name: Install Depedencies
        run: pip install -r requirements.txt
      - name: Test
        run: |
          pip install pytest
          pytest
